development:
  SENDGRID_USER: "rubyonrails.training"
  SENDGRID_PASSWORD: "RubyOnRails4.1"
  SENDGRID_HEROKU_PASSWORD: "7sxo4wv54353"
  SENDGRID_HEROKU_USER: "app35150464@heroku.com"
  DOMAIN: "crm-prz.24tm.pl"
  DEFAULT_AVATAR: /uploads/user/avatar/default_avatar.gif
test:
  DEFAULT_AVATAR: /uploads/user/avatar/default_avatar.gif
production:
  DEFAULT_AVATAR: /uploads/user/avatar/default_avatar.gif
  SENDGRID_HEROKU_PASSWORD: "7sxo4wv54353"
  SENDGRID_HEROKU_USER: "app35150464@heroku.com"
